### ISSUE TITLE
Send Button cannot be seen

### ISSUE THREAD

**Issue by MarkTheHopeful** [waleko/KotlinAndroidSFTMessenger#12]
On some real phones (like mine) the button to send a message is not seen. Just the field to write it, without any buttons.

**Comment by waleko** [comment]
@MarkTheHopeful Can we have a screenshot?

**Comment by MarkTheHopeful** [comment]
![изображение](https://user-images.githubusercontent.com/38182188/81500510-5af94480-92db-11ea-9040-3bc52185ed86.png)
![изображение](https://user-images.githubusercontent.com/38182188/81500523-60ef2580-92db-11ea-9534-0445619c3550.png)
![изображение](https://user-images.githubusercontent.com/38182188/81500527-651b4300-92db-11ea-97fc-74d91071819e.png)

**Comment by khbminus** [comment]
I can't reproduce your bug in virtual pixel 2 with android 6.0.
![image](https://user-images.githubusercontent.com/18504758/81555447-42e3fc80-9391-11ea-99d2-a68f2e4b5623.png)

@MarkTheHopeful,  What device do you use?

Or it can be just firmware bug.

**Comment by waleko** [comment]
@MarkTheHopeful Could you also try deleting and reinstalling the app?

**Comment by MarkTheHopeful** [comment]
Yes, I tried, it didn't work. 
Device: Samsung Galaxy J2 Prime SM-G532F
Android version is 6.0.1

**Comment by MarkTheHopeful** [comment]
Probably, the reason is the hardcoded android:layout_width="347dp" in EditText in @+id/messageText (activity_chat.xml)

**Comment by waleko** [comment]
@MarkTheHopeful Is this solved?

**Comment by MarkTheHopeful** [comment]
Still not, I will fix it after I finish my current task because this problem affects only me.
